# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 780c7cc1e37605425353755902a3afd47c79349cda75c9a498c5476f6d9eea2310941aecbecb571ce3d354721d0068720825c2f8c251e68063e47e418ec737db

test:
  secret_key_base: ac4bcd6bffe5b027c995f16ac9f789108b04af7f701ec63b0c7311464ce0c00fa9af192970655e12e2991f88fa06fc21e042bcfe5865eb7b0ed8ebfd010762ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
